print("ALUGUEL DO CARRO")
print()
dias = int(input("Quantos dias alugados? "))
Km = float(input("Quantos Km rodados? "))
PAGO = (dias * 60) + (Km * 0.15)
print("O total a pagar é de R${:.2f}".format(PAGO))
