print("Digite sua frase baixo \n")
frase = input("").strip().upper().replace(" ", "")
print("A letra A aparece {} vezes na frase.".format(frase.count("A")))
print("A letra A apareceu na posição {}".format(frase.find("A")))
print("A ultima letra A apareceu na posição {}".format(frase.rfind("A")))